version: '3.7'

services:
  postgres:
    container_name: postgres
    image: 'postgres:12.3'
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    ports:
      - "5432:5432"